Make test-syntax cleaner in phnerg

diff --git a/phnerg b/phnerg
--- a/phnerg
+++ b/phnerg
@@ -25,8 +25,8 @@
 
 ## EDIT THESE
 vidsize='3200x1800'
-audchan='2'
-withcamera='1'
+audchan=2
+withcamera=1
 scaleflags='-filter:v scale=1360:-1'
 fps=25
 hwaccel='vaapi'
@@ -39,9 +39,10 @@ scriptdir="$(dirname "$(readlink -e "${0}")")"
 while test ${#} -ne 0; do
     case "${1}" in
         dual) vidsize='5920x1800'; shift;;
-        mono) audchan='1'; shift;;
-        nocamera) withcamera=''; shift;;
+        mono) audchan=1; shift;;
+        nocamera) withcamera=0; shift;;
         noscale) scaleflags=''; shift;;
+        *) printf 'Invalid arg "%s"\n' "${1}" >&2; exit 1;;
     esac
 done
 
@@ -52,7 +53,7 @@ screencast_command='ffmpeg \
     ~/Desktop/screencast-$(date +%Y%m%d%H%M%S).mkv
 '
 
-if test -z "${withcamera}"; then
+if test ${withcamera} -eq 0; then
     eval "exec ${screencast_command}"
 else
     pid=$("${scriptdir}/camera-mirror")
